import React from 'react';

export default function TermsView() {
  return (
    <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8 space-y-6 font-sans text-sm text-slate-705 leading-relaxed" id="terms-conditions-document">
      <h1 className="font-display text-3xl font-extrabold tracking-tight text-slate-900">Terms & Conditions</h1>
      <p className="text-xs text-slate-400 font-mono">Last modified: June 2, 2026</p>

      <p>
        These standard user agreements organize the conditions surrounding your engagement with GROVIADS digital platforms, virtual assistants, growth projections, and diagnostic audit services.
      </p>

      <h2 className="font-display text-lg font-bold text-slate-900 pt-4">1. Diagnostic Audits Disclaimers</h2>
      <p>
        Any scoring indexes, performance recommendations, and chronological timelines generated by our AI diagnostic crawler or server-side API models represent optimal strategic planning forecasts. Actual revenue metrics reflect operational implementation, campaign investments, and local product conditions.
      </p>

      <h2 className="font-display text-lg font-bold text-slate-900 pt-4">2. Free Strategy Briefings Conditions</h2>
      <p>
        Our preliminary 30-minute consultation briefings are entirely free of financial commitment. Scheduling a session reserves administrative advisory hours. In the event of calendar conflicts, we request cancellations be submitted at least 4 hours in advance.
      </p>

      <h2 className="font-display text-lg font-bold text-slate-900 pt-4">3. Intellectual Property Rights</h2>
      <p>
        All website assets, interactive charts, custom blog topics catalogs, and visual logo designs representing GROVIADS are our sole property. Standard business entities are permitted copy-access on individual topic keys purely for personal growth strategy planning.
      </p>
    </div>
  );
}
